import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

// The one list of languages. A new language is an entry here plus a
// dictionary below, the same way a new feed is one entry in TABS. Nothing
// else in the app holds a list of language codes.
//
// `endonym` is the language named in its own language, never translated: a
// reader who cannot read English still has to be able to find their own row
// in the menu, so "Español" stays "Español" in every dictionary.
// `htmlLang` is the BCP-47 tag for <html lang>, which screen readers read to
// pick a voice. `speechLang` is the tag handed to the browser's own speech
// synthesis when the natural voice is unavailable.
export const LANGUAGES = [
  { code: "en", endonym: "English", htmlLang: "en", speechLang: "en-US" },
  { code: "es", endonym: "Español", htmlLang: "es", speechLang: "es-ES" },
  { code: "zh", endonym: "中文（简体）", htmlLang: "zh-Hans", speechLang: "zh-CN" },
  { code: "hi", endonym: "हिन्दी", htmlLang: "hi", speechLang: "hi-IN" },
  { code: "fil", endonym: "Filipino", htmlLang: "fil", speechLang: "fil-PH" },
  { code: "vi", endonym: "Tiếng Việt", htmlLang: "vi", speechLang: "vi-VN" },
  { code: "ru", endonym: "Русский", htmlLang: "ru", speechLang: "ru-RU" },
  { code: "ja", endonym: "日本語", htmlLang: "ja", speechLang: "ja-JP" },
  { code: "ko", endonym: "한국어", htmlLang: "ko", speechLang: "ko-KR" },
  { code: "pt", endonym: "Português", htmlLang: "pt-BR", speechLang: "pt-BR" },
  { code: "fr", endonym: "Français", htmlLang: "fr", speechLang: "fr-FR" },
] as const;

export type Language = (typeof LANGUAGES)[number]["code"];
type Key = keyof typeof EN;

export function languageInfo(code: Language) {
  return LANGUAGES.find((entry) => entry.code === code) ?? LANGUAGES[0];
}

const EN = {
  language: "Language",
  read: "Read",
  askAi: "Ask AI",
  about: "About",
  accessibility: "Accessibility",
  displayPreferences: "Choose display preferences",
  largerText: "Larger text",
  higherContrast: "Higher contrast",
  reduceMotion: "Reduce motion",
  colorVision: "Color vision",
  standardColors: "Standard colors",
  redGreen: "Red-green support",
  blueYellow: "Blue-yellow support",
  noColor: "No color",
  colorHelp: "Labels and icons always carry the meaning too.",
  readCard: "Read this card aloud",
  readLesson: "Read this lesson aloud",
  readAnswer: "Read answer aloud",
  readStory: "Read this story aloud",
  stopReading: "Stop reading",
  preparingVoice: "Preparing natural voice…",
  voiceDisclosure: "AI-generated voice",
  aiTranslated: "AI translated",
  viewEnglish: "View original English",
  showTranslation: "Show translation",
  translating: "Translating…",
  translationError: "Translation is unavailable right now.",
  source: "Source",
  news: "AI Sec News",
  learn: "AI Sec Learn",
  jobs: "AI Sec Jobs",
  newsIntro: "Real reports of AI used to trick people, rewritten in plain language.",
  learnIntro: "Free guides for understanding and defending AI systems.",
  jobsIntro: "Open roles where AI and security meet.",
  flipScam: "See how this works",
  flipCourse: "What you will learn",
  flipJob: "What they want",
  backToStory: "Back to the story",
  backToGuide: "Back to the guide",
  backToRole: "Back to the role",
  notWrittenUp: "This one is still being written up. Check back after the next crawl.",
  whoItIsFor: "Who it is for",
  howToStart: "How to start",
  timeNeeded: "Time needed",
  howToApply: "How to apply",
  openingLesson: "Opening the lesson…",
  warningSigns: "Warning signs",
  whyItWorks: "Why it works",
  whatYouSaw: "What you saw",
  whatWasReal: "What was real",
  teachMe: "Teach me how this works",
  writingLesson: "Writing your lesson…",
  askAnything: "Ask anything about this scam",
  askHelp: "Do not include passwords, codes, or account numbers.",
  askPlaceholder: "How would I check if it is really them?",
  asking: "Asking…",
  askButton: "Ask",
  correctAnswer: "Correct answer",
  yourAnswer: "Your answer",
  thatsTheOne: "That's the one.",
  notQuite: "Not quite.",
  sendFailed: "That did not come through. Try again in a moment.",
  saveFailed: "That answer did not save. Try again in a moment.",
  openGuide: "Open the guide",
  seeFullPosting: "See the full posting",
  trySpotting: "Try spotting it yourself",
  howThisWorks: "How this works",
  whatGivesItAway: "What gives it away",
  newTab: "(opens in a new tab)",
} as const;

const ES: Record<Key, string> = {
  language: "Idioma", read: "Leer", askAi: "Preguntar a la IA", about: "Acerca de",
  accessibility: "Accesibilidad", displayPreferences: "Elige tus preferencias de visualización",
  largerText: "Texto más grande", higherContrast: "Mayor contraste", reduceMotion: "Reducir movimiento",
  colorVision: "Visión del color", standardColors: "Colores estándar", redGreen: "Ayuda para rojo y verde",
  blueYellow: "Ayuda para azul y amarillo", noColor: "Sin color",
  colorHelp: "Las etiquetas y los iconos también comunican el significado.",
  readCard: "Escuchar esta tarjeta", readLesson: "Escuchar esta lección", readAnswer: "Escuchar respuesta",
  readStory: "Escuchar esta historia", stopReading: "Detener lectura", preparingVoice: "Preparando voz natural…",
  voiceDisclosure: "Voz generada por IA", aiTranslated: "Traducido por IA", viewEnglish: "Ver inglés original",
  showTranslation: "Mostrar traducción", translating: "Traduciendo…",
  translationError: "La traducción no está disponible ahora.", source: "Fuente",
  news: "Noticias de seguridad de IA", learn: "Aprender seguridad de IA", jobs: "Empleos de seguridad de IA",
  newsIntro: "Informes reales sobre el uso de IA para engañar, explicados con palabras sencillas.",
  learnIntro: "Guías gratuitas para comprender y defender sistemas de IA.",
  jobsIntro: "Puestos abiertos donde se unen la IA y la seguridad.",
  flipScam: "Mira cómo funciona",
  flipCourse: "Lo que aprenderás",
  flipJob: "Lo que buscan",
  backToStory: "Volver a la noticia",
  backToGuide: "Volver a la guía",
  backToRole: "Volver al puesto",
  notWrittenUp: "Este todavía se está redactando. Vuelve después de la próxima búsqueda.",
  whoItIsFor: "Para quién es",
  howToStart: "Cómo empezar",
  timeNeeded: "Tiempo necesario",
  howToApply: "Cómo postular",
  openingLesson: "Abriendo la lección…",
  warningSigns: "Señales de alerta",
  whyItWorks: "Por qué funciona",
  whatYouSaw: "Lo que viste",
  whatWasReal: "Lo que era real",
  teachMe: "Explícame cómo funciona",
  writingLesson: "Escribiendo tu lección…",
  askAnything: "Pregunta lo que quieras sobre este engaño",
  askHelp: "No incluyas contraseñas, códigos ni números de cuenta.",
  askPlaceholder: "¿Cómo compruebo si de verdad son ellos?",
  asking: "Preguntando…",
  askButton: "Preguntar",
  correctAnswer: "Respuesta correcta",
  yourAnswer: "Tu respuesta",
  thatsTheOne: "Esa es.",
  notQuite: "No exactamente.",
  sendFailed: "Eso no llegó. Inténtalo de nuevo en un momento.",
  saveFailed: "Esa respuesta no se guardó. Inténtalo de nuevo en un momento.",
  openGuide: "Abrir la guía",
  seeFullPosting: "Ver el anuncio completo",
  trySpotting: "Intenta detectarlo tú mismo",
  howThisWorks: "Cómo funciona esto",
  whatGivesItAway: "Lo que lo delata",
  newTab: "(se abre en una pestaña nueva)",
};

const ZH: Record<Key, string> = {
  language: "语言", read: "阅读", askAi: "询问 AI", about: "关于",
  accessibility: "无障碍", displayPreferences: "选择显示偏好",
  largerText: "更大的文字", higherContrast: "更高对比度", reduceMotion: "减少动效",
  colorVision: "色觉", standardColors: "标准颜色", redGreen: "红绿色辨识支持",
  blueYellow: "蓝黄色辨识支持", noColor: "不使用颜色",
  colorHelp: "标签和图标也始终传达同样的含义。",
  readCard: "朗读这张卡片", readLesson: "朗读这节课", readAnswer: "朗读答案",
  readStory: "朗读这篇报道", stopReading: "停止朗读", preparingVoice: "正在准备自然语音…",
  voiceDisclosure: "AI 生成的语音", aiTranslated: "AI 翻译", viewEnglish: "查看英文原文",
  showTranslation: "显示翻译", translating: "正在翻译…",
  translationError: "目前无法提供翻译。", source: "来源",
  news: "AI 安全新闻", learn: "学习 AI 安全", jobs: "AI 安全职位",
  newsIntro: "有人利用 AI 行骗的真实报道，用简单的话重新讲述。",
  learnIntro: "免费指南，帮助你理解和防护 AI 系统。",
  jobsIntro: "AI 与安全交汇的空缺职位。",
  flipScam: "看看这是怎么回事",
  flipCourse: "你将学到什么",
  flipJob: "他们想要什么",
  backToStory: "返回这则报道",
  backToGuide: "返回这份指南",
  backToRole: "返回这个职位",
  notWrittenUp: "这一条还在整理中。下次抓取后再来看看。",
  whoItIsFor: "适合谁",
  howToStart: "如何开始",
  timeNeeded: "所需时间",
  howToApply: "如何申请",
  openingLesson: "正在打开这节课…",
  warningSigns: "警示信号",
  whyItWorks: "为什么会奏效",
  whatYouSaw: "你看到的",
  whatWasReal: "真实情况",
  teachMe: "教我这是怎么回事",
  writingLesson: "正在写你的课程…",
  askAnything: "关于这个骗局，你可以随便问",
  askHelp: "不要填写密码、验证码或账号。",
  askPlaceholder: "我怎么确认对方真的是他们？",
  asking: "正在提问…",
  askButton: "提问",
  correctAnswer: "正确答案",
  yourAnswer: "你的答案",
  thatsTheOne: "就是这个。",
  notQuite: "还不太对。",
  sendFailed: "没有发送成功。请稍后再试。",
  saveFailed: "答案没有保存。请稍后再试。",
  openGuide: "打开指南",
  seeFullPosting: "查看完整职位",
  trySpotting: "自己来试着找出来",
  howThisWorks: "这是怎么运作的",
  whatGivesItAway: "哪里露了馅",
  newTab: "（在新标签页中打开）",
};

const HI: Record<Key, string> = {
  language: "भाषा", read: "पढ़ें", askAi: "AI से पूछें", about: "परिचय",
  accessibility: "सुगम्यता", displayPreferences: "प्रदर्शन की पसंद चुनें",
  largerText: "बड़ा टेक्स्ट", higherContrast: "अधिक कंट्रास्ट", reduceMotion: "गति कम करें",
  colorVision: "रंग दृष्टि", standardColors: "सामान्य रंग", redGreen: "लाल-हरे के लिए सहायता",
  blueYellow: "नीले-पीले के लिए सहायता", noColor: "बिना रंग",
  colorHelp: "लेबल और आइकन भी हमेशा अर्थ बताते हैं।",
  readCard: "यह कार्ड सुनें", readLesson: "यह पाठ सुनें", readAnswer: "उत्तर सुनें",
  readStory: "यह खबर सुनें", stopReading: "पढ़ना बंद करें", preparingVoice: "स्वाभाविक आवाज़ तैयार हो रही है…",
  voiceDisclosure: "AI से बनाई गई आवाज़", aiTranslated: "AI ने अनुवाद किया", viewEnglish: "मूल अंग्रेज़ी देखें",
  showTranslation: "अनुवाद दिखाएं", translating: "अनुवाद हो रहा है…",
  translationError: "अनुवाद अभी उपलब्ध नहीं है।", source: "स्रोत",
  news: "AI सुरक्षा समाचार", learn: "AI सुरक्षा सीखें", jobs: "AI सुरक्षा नौकरियां",
  newsIntro: "AI से लोगों को ठगने की सच्ची खबरें, आसान शब्दों में।",
  learnIntro: "AI सिस्टम को समझने और बचाने के लिए मुफ़्त गाइड।",
  jobsIntro: "ऐसी नौकरियां जहां AI और सुरक्षा मिलते हैं।",
  flipScam: "देखें यह कैसे होता है",
  flipCourse: "आप क्या सीखेंगे",
  flipJob: "उन्हें क्या चाहिए",
  backToStory: "खबर पर वापस जाएं",
  backToGuide: "गाइड पर वापस जाएं",
  backToRole: "नौकरी पर वापस जाएं",
  notWrittenUp: "यह अभी तैयार हो रहा है। अगली बार फिर देखें।",
  whoItIsFor: "यह किसके लिए है",
  howToStart: "शुरू कैसे करें",
  timeNeeded: "लगने वाला समय",
  howToApply: "आवेदन कैसे करें",
  openingLesson: "पाठ खुल रहा है…",
  warningSigns: "चेतावनी के संकेत",
  whyItWorks: "यह क्यों काम करता है",
  whatYouSaw: "आपने क्या देखा",
  whatWasReal: "असल में क्या था",
  teachMe: "मुझे समझाएं यह कैसे काम करता है",
  writingLesson: "आपका पाठ लिखा जा रहा है…",
  askAnything: "इस ठगी के बारे में कुछ भी पूछें",
  askHelp: "पासवर्ड, कोड या खाता नंबर न लिखें।",
  askPlaceholder: "मैं कैसे जांचूं कि यह सचमुच वही हैं?",
  asking: "पूछा जा रहा है…",
  askButton: "पूछें",
  correctAnswer: "सही जवाब",
  yourAnswer: "आपका जवाब",
  thatsTheOne: "यही सही है।",
  notQuite: "बिल्कुल नहीं।",
  sendFailed: "यह नहीं पहुंचा। थोड़ी देर बाद फिर कोशिश करें।",
  saveFailed: "जवाब सेव नहीं हुआ। थोड़ी देर बाद फिर कोशिश करें।",
  openGuide: "गाइड खोलें",
  seeFullPosting: "पूरी जानकारी देखें",
  trySpotting: "खुद पहचानने की कोशिश करें",
  howThisWorks: "यह कैसे काम करता है",
  whatGivesItAway: "इसे क्या पकड़वाता है",
  newTab: "(नए टैब में खुलता है)",
};

const FIL: Record<Key, string> = {
  language: "Wika", read: "Basahin", askAi: "Magtanong sa AI", about: "Tungkol",
  accessibility: "Accessibility", displayPreferences: "Pumili ng mga setting sa display",
  largerText: "Mas malaking teksto", higherContrast: "Mas mataas na contrast", reduceMotion: "Bawasan ang galaw",
  colorVision: "Paningin sa kulay", standardColors: "Karaniwang mga kulay", redGreen: "Tulong sa pula at berde",
  blueYellow: "Tulong sa asul at dilaw", noColor: "Walang kulay",
  colorHelp: "May label at icon din para malinaw ang kahulugan.",
  readCard: "Pakinggan ang card", readLesson: "Pakinggan ang aralin", readAnswer: "Pakinggan ang sagot",
  readStory: "Pakinggan ang kuwento", stopReading: "Itigil ang pagbasa", preparingVoice: "Inihahanda ang natural na boses…",
  voiceDisclosure: "Boses na ginawa ng AI", aiTranslated: "Isinalin ng AI", viewEnglish: "Tingnan ang orihinal na English",
  showTranslation: "Ipakita ang salin", translating: "Isinasalin…",
  translationError: "Hindi available ngayon ang salin.", source: "Pinagmulan",
  news: "Balita sa AI Security", learn: "Matuto ng AI Security", jobs: "Mga Trabaho sa AI Security",
  newsIntro: "Mga totoong ulat tungkol sa panlilinlang gamit ang AI, ipinaliwanag sa simpleng salita.",
  learnIntro: "Libreng gabay sa pag-unawa at pagprotekta sa mga AI system.",
  jobsIntro: "Mga bukas na trabaho na pinagsasama ang AI at seguridad.",
  flipScam: "Tingnan kung paano ito gumagana",
  flipCourse: "Ano ang matututuhan mo",
  flipJob: "Ano ang hinahanap nila",
  backToStory: "Bumalik sa kuwento",
  backToGuide: "Bumalik sa gabay",
  backToRole: "Bumalik sa trabaho",
  notWrittenUp: "Ginagawa pa ito. Balikan mo pagkatapos ng susunod na crawl.",
  whoItIsFor: "Para kanino ito",
  howToStart: "Paano magsimula",
  timeNeeded: "Oras na kailangan",
  howToApply: "Paano mag-apply",
  openingLesson: "Binubuksan ang aralin…",
  warningSigns: "Mga babala",
  whyItWorks: "Bakit ito gumagana",
  whatYouSaw: "Ang nakita mo",
  whatWasReal: "Ang totoo",
  teachMe: "Ituro mo kung paano ito gumagana",
  writingLesson: "Isinusulat ang iyong aralin…",
  askAnything: "Magtanong ng kahit ano tungkol sa panlolokong ito",
  askHelp: "Huwag maglagay ng password, code, o account number.",
  askPlaceholder: "Paano ko malalaman kung sila talaga iyon?",
  asking: "Nagtatanong…",
  askButton: "Itanong",
  correctAnswer: "Tamang sagot",
  yourAnswer: "Ang sagot mo",
  thatsTheOne: "Tama iyan.",
  notQuite: "Hindi masyado.",
  sendFailed: "Hindi ito nakarating. Subukan ulit maya-maya.",
  saveFailed: "Hindi na-save ang sagot. Subukan ulit maya-maya.",
  openGuide: "Buksan ang gabay",
  seeFullPosting: "Tingnan ang buong post",
  trySpotting: "Subukan mong tukuyin ito",
  howThisWorks: "Paano ito nangyayari",
  whatGivesItAway: "Ano ang nagbibigay ng senyales",
  newTab: "(bubukas sa bagong tab)",
};

const VI: Record<Key, string> = {
  language: "Ngôn ngữ", read: "Đọc", askAi: "Hỏi AI", about: "Giới thiệu",
  accessibility: "Trợ năng", displayPreferences: "Chọn tùy chọn hiển thị",
  largerText: "Chữ lớn hơn", higherContrast: "Tương phản cao hơn", reduceMotion: "Giảm chuyển động",
  colorVision: "Thị giác màu", standardColors: "Màu tiêu chuẩn", redGreen: "Hỗ trợ đỏ và xanh lá",
  blueYellow: "Hỗ trợ xanh dương và vàng", noColor: "Không dùng màu",
  colorHelp: "Nhãn và biểu tượng luôn truyền tải cùng ý nghĩa.",
  readCard: "Nghe thẻ này", readLesson: "Nghe bài học này", readAnswer: "Nghe câu trả lời",
  readStory: "Nghe bài này", stopReading: "Dừng đọc", preparingVoice: "Đang chuẩn bị giọng tự nhiên…",
  voiceDisclosure: "Giọng nói do AI tạo", aiTranslated: "Dịch bằng AI", viewEnglish: "Xem bản tiếng Anh gốc",
  showTranslation: "Hiện bản dịch", translating: "Đang dịch…",
  translationError: "Hiện chưa có bản dịch.", source: "Nguồn",
  news: "Tin an ninh AI", learn: "Học an ninh AI", jobs: "Việc làm an ninh AI",
  newsIntro: "Những vụ thật về việc dùng AI để lừa người, kể lại bằng lời đơn giản.",
  learnIntro: "Hướng dẫn miễn phí để hiểu và bảo vệ hệ thống AI.",
  jobsIntro: "Những vị trí đang tuyển nơi AI và an ninh gặp nhau.",
  flipScam: "Xem cách nó hoạt động",
  flipCourse: "Bạn sẽ học được gì",
  flipJob: "Họ cần gì",
  backToStory: "Quay lại bài viết",
  backToGuide: "Quay lại hướng dẫn",
  backToRole: "Quay lại vị trí",
  notWrittenUp: "Mục này đang được soạn. Hãy quay lại sau lần thu thập tiếp theo.",
  whoItIsFor: "Dành cho ai",
  howToStart: "Bắt đầu thế nào",
  timeNeeded: "Thời gian cần",
  howToApply: "Cách ứng tuyển",
  openingLesson: "Đang mở bài học…",
  warningSigns: "Dấu hiệu cảnh báo",
  whyItWorks: "Vì sao nó hiệu quả",
  whatYouSaw: "Điều bạn thấy",
  whatWasReal: "Sự thật",
  teachMe: "Giải thích cho tôi cách nó hoạt động",
  writingLesson: "Đang viết bài học của bạn…",
  askAnything: "Hỏi bất cứ điều gì về vụ lừa này",
  askHelp: "Đừng nhập mật khẩu, mã hoặc số tài khoản.",
  askPlaceholder: "Làm sao để biết đúng là họ?",
  asking: "Đang hỏi…",
  askButton: "Hỏi",
  correctAnswer: "Đáp án đúng",
  yourAnswer: "Câu trả lời của bạn",
  thatsTheOne: "Chính xác.",
  notQuite: "Chưa đúng.",
  sendFailed: "Không gửi được. Hãy thử lại sau giây lát.",
  saveFailed: "Câu trả lời chưa được lưu. Hãy thử lại sau giây lát.",
  openGuide: "Mở hướng dẫn",
  seeFullPosting: "Xem tin tuyển đầy đủ",
  trySpotting: "Tự thử nhận ra xem",
  howThisWorks: "Cách thức diễn ra",
  whatGivesItAway: "Điều gì làm lộ ra",
  newTab: "(mở trong tab mới)",
};

const RU: Record<Key, string> = {
  language: "Язык", read: "Читать", askAi: "Спросить ИИ", about: "О проекте",
  accessibility: "Доступность", displayPreferences: "Выберите настройки отображения",
  largerText: "Крупный текст", higherContrast: "Выше контраст", reduceMotion: "Меньше анимации",
  colorVision: "Цветовое зрение", standardColors: "Обычные цвета", redGreen: "Поддержка красного и зелёного",
  blueYellow: "Поддержка синего и жёлтого", noColor: "Без цвета",
  colorHelp: "Подписи и значки тоже всегда передают смысл.",
  readCard: "Прослушать карточку", readLesson: "Прослушать урок", readAnswer: "Прослушать ответ",
  readStory: "Прослушать материал", stopReading: "Остановить чтение", preparingVoice: "Готовим естественный голос…",
  voiceDisclosure: "Голос создан ИИ", aiTranslated: "Перевод сделан ИИ", viewEnglish: "Показать оригинал на английском",
  showTranslation: "Показать перевод", translating: "Переводим…",
  translationError: "Перевод сейчас недоступен.", source: "Источник",
  news: "Новости безопасности ИИ", learn: "Учить безопасность ИИ", jobs: "Работа в безопасности ИИ",
  newsIntro: "Настоящие случаи, когда ИИ использовали для обмана, простыми словами.",
  learnIntro: "Бесплатные руководства, как понимать и защищать системы ИИ.",
  jobsIntro: "Открытые вакансии на стыке ИИ и безопасности.",
  flipScam: "Посмотрите, как это работает",
  flipCourse: "Чему вы научитесь",
  flipJob: "Что они ищут",
  backToStory: "Вернуться к материалу",
  backToGuide: "Вернуться к руководству",
  backToRole: "Вернуться к вакансии",
  notWrittenUp: "Этот материал ещё готовится. Загляните после следующего обхода.",
  whoItIsFor: "Кому подходит",
  howToStart: "С чего начать",
  timeNeeded: "Сколько времени",
  howToApply: "Как откликнуться",
  openingLesson: "Открываем урок…",
  warningSigns: "Тревожные признаки",
  whyItWorks: "Почему это срабатывает",
  whatYouSaw: "Что вы видели",
  whatWasReal: "Что было на самом деле",
  teachMe: "Объясните, как это работает",
  writingLesson: "Пишем ваш урок…",
  askAnything: "Спросите что угодно об этом обмане",
  askHelp: "Не указывайте пароли, коды и номера счетов.",
  askPlaceholder: "Как проверить, что это действительно они?",
  asking: "Отправляем вопрос…",
  askButton: "Спросить",
  correctAnswer: "Правильный ответ",
  yourAnswer: "Ваш ответ",
  thatsTheOne: "Верно.",
  notQuite: "Не совсем.",
  sendFailed: "Не отправилось. Попробуйте ещё раз через минуту.",
  saveFailed: "Ответ не сохранился. Попробуйте ещё раз через минуту.",
  openGuide: "Открыть руководство",
  seeFullPosting: "Смотреть вакансию целиком",
  trySpotting: "Попробуйте распознать сами",
  howThisWorks: "Как это устроено",
  whatGivesItAway: "Что выдаёт обман",
  newTab: "(откроется в новой вкладке)",
};

const JA: Record<Key, string> = {
  language: "言語", read: "読む", askAi: "AIに聞く", about: "このサイトについて",
  accessibility: "アクセシビリティ", displayPreferences: "表示の設定を選ぶ",
  largerText: "文字を大きく", higherContrast: "コントラストを高く", reduceMotion: "動きを減らす",
  colorVision: "色覚", standardColors: "標準の色", redGreen: "赤と緑のサポート",
  blueYellow: "青と黄のサポート", noColor: "色を使わない",
  colorHelp: "ラベルとアイコンでも同じ意味が伝わります。",
  readCard: "このカードを読み上げる", readLesson: "このレッスンを読み上げる", readAnswer: "答えを読み上げる",
  readStory: "この記事を読み上げる", stopReading: "読み上げを止める", preparingVoice: "自然な音声を準備中…",
  voiceDisclosure: "AIが生成した音声", aiTranslated: "AIによる翻訳", viewEnglish: "英語の原文を見る",
  showTranslation: "翻訳を表示", translating: "翻訳中…",
  translationError: "今は翻訳を利用できません。", source: "出典",
  news: "AIセキュリティニュース", learn: "AIセキュリティを学ぶ", jobs: "AIセキュリティの求人",
  newsIntro: "AIを使って人をだました実際の事例を、やさしい言葉で伝えます。",
  learnIntro: "AIの仕組みを理解し、守るための無料ガイド。",
  jobsIntro: "AIとセキュリティが重なる求人。",
  flipScam: "手口を見る",
  flipCourse: "学べること",
  flipJob: "求められること",
  backToStory: "記事に戻る",
  backToGuide: "ガイドに戻る",
  backToRole: "求人に戻る",
  notWrittenUp: "これはまだ作成中です。次の収集のあとにご覧ください。",
  whoItIsFor: "対象となる人",
  howToStart: "始め方",
  timeNeeded: "所要時間",
  howToApply: "応募の方法",
  openingLesson: "レッスンを開いています…",
  warningSigns: "危険なサイン",
  whyItWorks: "なぜ引っかかるのか",
  whatYouSaw: "あなたが見たもの",
  whatWasReal: "実際のこと",
  teachMe: "この手口を教えて",
  writingLesson: "レッスンを作成しています…",
  askAnything: "この手口について何でも聞いてください",
  askHelp: "パスワードや認証コード、口座番号は書かないでください。",
  askPlaceholder: "本人かどうか、どう確かめますか？",
  asking: "質問中…",
  askButton: "質問する",
  correctAnswer: "正解",
  yourAnswer: "あなたの答え",
  thatsTheOne: "そのとおりです。",
  notQuite: "惜しいです。",
  sendFailed: "送信できませんでした。少し経ってからもう一度お試しください。",
  saveFailed: "答えを保存できませんでした。少し経ってからもう一度お試しください。",
  openGuide: "ガイドを開く",
  seeFullPosting: "求人の全文を見る",
  trySpotting: "自分で見抜いてみる",
  howThisWorks: "手口の流れ",
  whatGivesItAway: "見破るポイント",
  newTab: "（新しいタブで開きます）",
};

const KO: Record<Key, string> = {
  language: "언어", read: "읽기", askAi: "AI에게 묻기", about: "소개",
  accessibility: "접근성", displayPreferences: "화면 설정 선택",
  largerText: "더 큰 글자", higherContrast: "더 높은 대비", reduceMotion: "움직임 줄이기",
  colorVision: "색각", standardColors: "기본 색상", redGreen: "빨강-초록 지원",
  blueYellow: "파랑-노랑 지원", noColor: "색 사용 안 함",
  colorHelp: "라벨과 아이콘도 항상 같은 의미를 전달합니다.",
  readCard: "이 카드 읽어주기", readLesson: "이 수업 읽어주기", readAnswer: "답 읽어주기",
  readStory: "이 기사 읽어주기", stopReading: "읽기 멈추기", preparingVoice: "자연스러운 음성 준비 중…",
  voiceDisclosure: "AI가 만든 음성", aiTranslated: "AI 번역", viewEnglish: "영어 원문 보기",
  showTranslation: "번역 보기", translating: "번역 중…",
  translationError: "지금은 번역을 이용할 수 없습니다.", source: "출처",
  news: "AI 보안 뉴스", learn: "AI 보안 배우기", jobs: "AI 보안 채용",
  newsIntro: "AI로 사람을 속인 실제 사례를 쉬운 말로 전합니다.",
  learnIntro: "AI 시스템을 이해하고 지키는 무료 안내서.",
  jobsIntro: "AI와 보안이 만나는 채용 공고.",
  flipScam: "수법 보기",
  flipCourse: "배우게 될 내용",
  flipJob: "요구 사항",
  backToStory: "기사로 돌아가기",
  backToGuide: "안내서로 돌아가기",
  backToRole: "채용 공고로 돌아가기",
  notWrittenUp: "아직 정리 중입니다. 다음 수집 후에 다시 확인해 주세요.",
  whoItIsFor: "이런 분께",
  howToStart: "시작하는 방법",
  timeNeeded: "걸리는 시간",
  howToApply: "지원 방법",
  openingLesson: "수업을 여는 중…",
  warningSigns: "위험 신호",
  whyItWorks: "왜 통하는가",
  whatYouSaw: "당신이 본 것",
  whatWasReal: "실제였던 것",
  teachMe: "이 수법을 알려주세요",
  writingLesson: "수업을 작성하는 중…",
  askAnything: "이 수법에 대해 무엇이든 물어보세요",
  askHelp: "비밀번호, 인증 코드, 계좌 번호는 입력하지 마세요.",
  askPlaceholder: "정말 그 사람인지 어떻게 확인하나요?",
  asking: "질문하는 중…",
  askButton: "질문",
  correctAnswer: "정답",
  yourAnswer: "내 답",
  thatsTheOne: "맞았어요.",
  notQuite: "아쉽네요.",
  sendFailed: "전송되지 않았습니다. 잠시 후 다시 시도해 주세요.",
  saveFailed: "답이 저장되지 않았습니다. 잠시 후 다시 시도해 주세요.",
  openGuide: "안내서 열기",
  seeFullPosting: "전체 공고 보기",
  trySpotting: "직접 찾아보기",
  howThisWorks: "이렇게 진행됩니다",
  whatGivesItAway: "들통나는 지점",
  newTab: "(새 탭에서 열림)",
};

const PT: Record<Key, string> = {
  language: "Idioma", read: "Ler", askAi: "Perguntar à IA", about: "Sobre",
  accessibility: "Acessibilidade", displayPreferences: "Escolha as preferências de exibição",
  largerText: "Texto maior", higherContrast: "Mais contraste", reduceMotion: "Reduzir movimento",
  colorVision: "Visão de cores", standardColors: "Cores padrão", redGreen: "Apoio para vermelho e verde",
  blueYellow: "Apoio para azul e amarelo", noColor: "Sem cor",
  colorHelp: "Os rótulos e os ícones também indicam o significado.",
  readCard: "Ouvir este cartão", readLesson: "Ouvir esta lição", readAnswer: "Ouvir a resposta",
  readStory: "Ouvir esta matéria", stopReading: "Parar a leitura", preparingVoice: "Preparando voz natural…",
  voiceDisclosure: "Voz gerada por IA", aiTranslated: "Traduzido por IA", viewEnglish: "Ver o inglês original",
  showTranslation: "Mostrar tradução", translating: "Traduzindo…",
  translationError: "A tradução não está disponível agora.", source: "Fonte",
  news: "Notícias de segurança em IA", learn: "Aprender segurança em IA", jobs: "Vagas em segurança de IA",
  newsIntro: "Casos reais de IA usada para enganar pessoas, contados em palavras simples.",
  learnIntro: "Guias gratuitos para entender e proteger sistemas de IA.",
  jobsIntro: "Vagas abertas onde IA e segurança se encontram.",
  flipScam: "Veja como funciona",
  flipCourse: "O que você vai aprender",
  flipJob: "O que eles procuram",
  backToStory: "Voltar para a matéria",
  backToGuide: "Voltar para o guia",
  backToRole: "Voltar para a vaga",
  notWrittenUp: "Este ainda está sendo escrito. Volte após a próxima coleta.",
  whoItIsFor: "Para quem é",
  howToStart: "Como começar",
  timeNeeded: "Tempo necessário",
  howToApply: "Como se candidatar",
  openingLesson: "Abrindo a lição…",
  warningSigns: "Sinais de alerta",
  whyItWorks: "Por que funciona",
  whatYouSaw: "O que você viu",
  whatWasReal: "O que era real",
  teachMe: "Me explique como funciona",
  writingLesson: "Escrevendo sua lição…",
  askAnything: "Pergunte o que quiser sobre este golpe",
  askHelp: "Não inclua senhas, códigos ou números de conta.",
  askPlaceholder: "Como eu confirmo se são mesmo eles?",
  asking: "Perguntando…",
  askButton: "Perguntar",
  correctAnswer: "Resposta correta",
  yourAnswer: "Sua resposta",
  thatsTheOne: "É essa.",
  notQuite: "Não é bem isso.",
  sendFailed: "Isso não foi enviado. Tente de novo em um instante.",
  saveFailed: "Essa resposta não foi salva. Tente de novo em um instante.",
  openGuide: "Abrir o guia",
  seeFullPosting: "Ver a vaga completa",
  trySpotting: "Tente identificar você mesmo",
  howThisWorks: "Como isso funciona",
  whatGivesItAway: "O que entrega o golpe",
  newTab: "(abre em uma nova aba)",
};

const FR: Record<Key, string> = {
  language: "Langue", read: "Lire", askAi: "Demander à l'IA", about: "À propos",
  accessibility: "Accessibilité", displayPreferences: "Choisissez vos préférences d'affichage",
  largerText: "Texte plus grand", higherContrast: "Plus de contraste", reduceMotion: "Réduire les animations",
  colorVision: "Vision des couleurs", standardColors: "Couleurs standard", redGreen: "Aide pour le rouge et le vert",
  blueYellow: "Aide pour le bleu et le jaune", noColor: "Sans couleur",
  colorHelp: "Les libellés et les icônes portent aussi le sens.",
  readCard: "Écouter cette fiche", readLesson: "Écouter cette leçon", readAnswer: "Écouter la réponse",
  readStory: "Écouter cet article", stopReading: "Arrêter la lecture", preparingVoice: "Préparation de la voix naturelle…",
  voiceDisclosure: "Voix générée par IA", aiTranslated: "Traduit par IA", viewEnglish: "Voir l'anglais d'origine",
  showTranslation: "Afficher la traduction", translating: "Traduction en cours…",
  translationError: "La traduction n'est pas disponible pour le moment.", source: "Source",
  news: "Actus sécurité de l'IA", learn: "Apprendre la sécurité de l'IA", jobs: "Emplois en sécurité de l'IA",
  newsIntro: "Des cas réels d'IA utilisée pour tromper les gens, en mots simples.",
  learnIntro: "Des guides gratuits pour comprendre et protéger les systèmes d'IA.",
  jobsIntro: "Des postes ouverts où l'IA et la sécurité se rejoignent.",
  flipScam: "Voir comment ça marche",
  flipCourse: "Ce que vous allez apprendre",
  flipJob: "Ce qu'ils recherchent",
  backToStory: "Retour à l'article",
  backToGuide: "Retour au guide",
  backToRole: "Retour au poste",
  notWrittenUp: "Celui-ci est encore en préparation. Revenez après la prochaine collecte.",
  whoItIsFor: "À qui cela s'adresse",
  howToStart: "Comment commencer",
  timeNeeded: "Temps nécessaire",
  howToApply: "Comment postuler",
  openingLesson: "Ouverture de la leçon…",
  warningSigns: "Signaux d'alerte",
  whyItWorks: "Pourquoi ça marche",
  whatYouSaw: "Ce que vous avez vu",
  whatWasReal: "Ce qui était réel",
  teachMe: "Expliquez-moi comment ça marche",
  writingLesson: "Rédaction de votre leçon…",
  askAnything: "Posez n'importe quelle question sur cette arnaque",
  askHelp: "N'indiquez pas de mots de passe, de codes ni de numéros de compte.",
  askPlaceholder: "Comment vérifier que c'est bien eux ?",
  asking: "Envoi de la question…",
  askButton: "Demander",
  correctAnswer: "Bonne réponse",
  yourAnswer: "Votre réponse",
  thatsTheOne: "C'est bien ça.",
  notQuite: "Pas tout à fait.",
  sendFailed: "Cela n'est pas passé. Réessayez dans un instant.",
  saveFailed: "Cette réponse n'a pas été enregistrée. Réessayez dans un instant.",
  openGuide: "Ouvrir le guide",
  seeFullPosting: "Voir l'annonce complète",
  trySpotting: "Essayez de le repérer vous-même",
  howThisWorks: "Comment cela se passe",
  whatGivesItAway: "Ce qui trahit l'arnaque",
  newTab: "(s'ouvre dans un nouvel onglet)",
};

const DICTIONARIES: Record<Language, Record<Key, string>> = {
  en: EN, es: ES, zh: ZH, hi: HI, fil: FIL, vi: VI, ru: RU, ja: JA, ko: KO, pt: PT, fr: FR,
};

const LanguageContext = createContext<{ language: Language; setLanguage: (value: Language) => void; t: (key: Key) => string } | null>(null);

function isLanguage(value: unknown): value is Language {
  return LANGUAGES.some((entry) => entry.code === value);
}

function initialLanguage(): Language {
  try {
    const saved = localStorage.getItem("flipsec-language");
    if (isLanguage(saved)) return saved;
  } catch { /* Use English when storage is unavailable. */ }
  return "en";
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(initialLanguage);
  useEffect(() => {
    document.documentElement.lang = languageInfo(language).htmlLang;
    try { localStorage.setItem("flipsec-language", language); } catch { /* Preference still applies. */ }
  }, [language]);
  return <LanguageContext.Provider value={{ language, setLanguage, t: (key) => DICTIONARIES[language][key] }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const value = useContext(LanguageContext);
  if (!value) throw new Error("useLanguage must be used inside LanguageProvider");
  return value;
}

export function LanguageSelector() {
  const { language, setLanguage, t } = useLanguage();
  return (
    <label className="flex min-h-11 items-center gap-2 text-base font-semibold text-navy">
      <span className="sr-only">{t("language")}</span>
      <select
        value={language}
        onChange={(event) => setLanguage(event.target.value as Language)}
        aria-label={t("language")}
        className="min-h-11 rounded-control border border-line bg-white px-2 text-base text-navy"
      >
        {/* Each option is tagged with its own lang so a screen reader
            pronounces the endonym in that language rather than reading
            "中文" through an English voice. */}
        {LANGUAGES.map((entry) => (
          <option key={entry.code} value={entry.code} lang={entry.htmlLang}>
            {entry.endonym}
          </option>
        ))}
      </select>
    </label>
  );
}
